[package]
name = "lsr"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = "2.33"
tabular = "0.1.4"
users = "0.11"
anyhow = "1.0.79"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
pretty_assertions = "1.4.0"
