[package]
name = "tailr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.79"
clap = "2.33"
num = "0.4"
regex = "1"
once_cell = "1"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
pretty_assertions = "1.4.0"
