[package]
name = "wcr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "2.33"
anyhow = "1.0.79"

[dev-dependencies]
pretty_assertions = "1.4.0"
assert_cmd = "2"
predicates = "2"
rand = "0.8"
