[package]
name = "findr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "2.33"
walkdir = "2"
regex = "1"
anyhow = "1.0.79"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
